pipeline {
  agent any

  tools {
    maven 'Maven3'
    jdk 'jdk21'
  }

  stages {

    stage('Java Check') {
      steps {
        bat 'echo JAVA_HOME=%JAVA_HOME%'
        bat 'java -version'
        bat 'where javac'
        bat 'javac -version'
        bat 'mvn -version'
      }
    }

    stage('Build') {
      steps {
        bat 'mvn -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        bat 'mvn -B test'
      }
      post {
        always {
          junit testResults: 'target/surefire-reports/*.xml',
                allowEmptyResults: true
        }
      }
    }

    stage('List deliver script') {
  steps {
    bat 'dir'
    bat 'dir jenkins'
    bat 'dir jenkins\\scripts'
    bat 'dir jenkins\\scripts\\deliver.ps1'
  }
}
    stage('Deliver') {
      steps {
        powershell '.\\jenkins\\scripts\\deliver.ps1'
      }
    }

    stage('Complete') {
      steps {
        echo 'Job Complete!'
      }
    }
  }
}
