pipeline {
  agent any

  tools {
    maven 'Maven3'
  }

  stages {
    stage('Build') {
      steps {
        script {
          if (isUnix()) {
            sh 'mvn -B -DskipTests clean package'
          } else {
            bat 'mvn -B -DskipTests clean package'
          }
        }
      }
    }

    stage('Test') {
      steps {
        script {
          if (isUnix()) {
            sh 'mvn -B test'
          } else {
            bat 'mvn -B test'
          }
        }
      }
      post {
        always {
          junit testResults: 'target/surefire-reports/*.xml', allowEmptyResults: true
        }
      }
    }

    stage('Deliver') {
      steps {
        script {
          if (isUnix()) {
            sh './jenkins/scripts/deliver.sh'
          } else {
            powershell '.\\jenkins\\scripts\\deliver.ps1'
          }
        }
      }
    }

    stage('Complete') {
      steps {
        echo 'Job Complete!'
      }
    }
  }
}
